### ISSUE TITLE
Definition of conformance

### ISSUE THREAD

**Issue by pietercolpaert** [constraintAutomaton/shape-index-specification#7]
When do you conform to the spec?

As the spec does not restrict shape languages, it can become tedious to make something that is arguably conforming to the spec. I would constrain it to SHACL and/or ShEx.

**Comment by constraintAutomaton** [comment]
I wanted something that more characterizes the mapping, constraints, and domain system, which is why I did not want to restrict the shape language. However, maybe it should be restricted in a pragmatic sense, or maybe we should recommend those two languages. My current implementation is in ShEx.

**Comment by pietercolpaert** [comment]
All depends on of course the goal you have by building the specification:
 * If you want other clients to implement this, then we need to make sure we’re more concrete
 * But also if we want servers to expose an index accordingly, we need to make sure the index data can be adopted by clients, and thus should be more concrete in terms of what exactly to expect

We should not make the same mistakes as other RDF based specs in the past that leave too much degrees of freedom, which will hinder adoption, and when it gets adopted after all, would hinder interoperability as a client only implementing SHACL would not be interoperable with a server exposing ShEx. Let’s be explicit.

**Comment by constraintAutomaton** [comment]
Now it explicitly ask for ShEx or SCHAL shapes.
